export const environment = {
  production: false,
  worldskillsAppId: 400,
  worldskillsPeopleAppId: 600,
  worldskillsApi: 'https://api.worldskills.show',
  worldskillsApiOrg: 'https://api.worldskills.show/org',
  worldskillsApiEvents: 'https://api.worldskills.show/events',
  worldskillsApiImages: 'https://api.worldskills.show/images',
  worldskillsClientId: '269f5d2',
  worldskillsAuthorizeUrl: 'https://auth.worldskills.show/oauth/authorize',
  worldskillsAuthorizeRedirect: 'https://events.worldskills.show/',
  worldskillsAuthorizeUserinfoEndpoint: 'https://auth.worldskills.show/auth/users/loggedIn',
  worldskillsAuthUriPatterns: ['api.worldskills.show'],
  environmentWarning: 'This is the staging environment. Changes in this environment might get overwritten.',
};
