export const environment = {
  production: true,
  worldskillsAppId: 400,
  worldskillsPeopleAppId: 600,
  worldskillsAuthAppId: 300,
  worldskillsApi: 'https://api.worldskills.show',
  worldskillsApiAuth: 'https://api.worldskills.show/auth',
  worldskillsApiOrg: 'https://api.worldskills.show/org',
  worldskillsApiPeople: 'https://api.worldskills.show/people',
  worldskillsApiEvents: 'https://api.worldskills.show/events',
  worldskillsApiImages: 'https://api.worldskills.show/images',
  worldskillsApiResources: 'https://api.worldskills.show/resources',
  worldskillsClientId: '49775efbb906',
  worldskillsAuthorizeUrl: 'https://auth.worldskills.show/oauth/authorize',
  worldskillsAuthorizeRedirect: 'https://api.worldskills.show/',
  worldskillsAuthorizeUserinfoEndpoint: 'https://events.worldskills.show/',
  worldskillsPuppeteer: 'https://api.worldskills.show/auth/sessions/operate_puppet',
  worldskillsAuthUriPatterns: ['api.worldskills.show'],
};
